#!/usr/bin/env python3
"""Build talkmap/org-locations.js from explicit talk coordinates, without a network.

Run `python3 talkmap.py` from any directory, or `python3 talkmap.py --check`
to check the committed data without writing it. Map metadata must use one-line
YAML scalars; other front-matter fields are ignored. Coordinates are city-level
unless map_precision explicitly says otherwise. Set map: false to omit a talk
that has no verified coordinates. No online geocoding or Python packages needed.
"""

import argparse
import datetime as dt
import json
import math
from pathlib import Path
import re
import sys


ROOT = Path(__file__).resolve().parent
FIELDS = {
    "title", "venue", "location", "permalink", "date", "type", "latitude",
    "longitude", "map_precision", "published", "map",
}


def scalar(value, path, key):
    """Read the deliberately small scalar subset used by map metadata."""
    value = value.strip()
    if value.startswith('"'):
        parsed, end = json.JSONDecoder().raw_decode(value)
        remainder = value[end:].strip()
        if remainder and not remainder.startswith("#"):
            raise ValueError(f"{path}: unexpected text after {key}")
        return parsed
    if value.startswith("'"):
        match = re.fullmatch(r"'((?:[^']|'')*)'\s*(?:#.*)?", value)
        if not match:
            raise ValueError(f"{path}: invalid single-quoted {key}")
        return match[1].replace("''", "'")
    value = re.split(r"\s+#", value, maxsplit=1)[0].strip()
    if value.startswith(("|", ">", "[", "{", "&", "*", "!")):
        raise ValueError(f"{path}: use a one-line scalar for map field {key}")
    return value


def read_metadata(path):
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines or lines[0] != "---":
        raise ValueError(f"{path}: missing YAML front matter")
    metadata = {}
    for line in lines[1:]:
        if line == "---":
            return metadata
        match = re.match(r"^([A-Za-z_][\w-]*):\s*(.*)$", line)
        if match and match[1] in FIELDS:
            metadata[match[1]] = scalar(match[2], path, match[1])
    raise ValueError(f"{path}: unclosed YAML front matter")


def build_data(source):
    talks = []
    for path in sorted(source.glob("*.md")):
        meta = read_metadata(path)
        if any(str(meta.get(key, "true")).lower() == "false" for key in ("published", "map")):
            continue
        if not meta.get("location"):
            continue
        required = ("title", "venue", "permalink", "date", "latitude", "longitude")
        missing = [key for key in required if not meta.get(key)]
        if missing:
            raise ValueError(f"{path}: missing {', '.join(missing)}; add coordinates or set map: false")
        lat, lon = float(meta["latitude"]), float(meta["longitude"])
        if not (math.isfinite(lat) and -90 <= lat <= 90 and math.isfinite(lon) and -180 <= lon <= 180):
            raise ValueError(f"{path}: invalid latitude/longitude")
        permalink = meta["permalink"]
        if not permalink.startswith("/") or permalink.startswith("//") or ".." in permalink.split("/"):
            raise ValueError(f"{path}: permalink must be a site-relative path")
        date = dt.date.fromisoformat(meta["date"]).isoformat()
        precision = meta.get("map_precision", "city")
        if precision not in ("city", "venue"):
            raise ValueError(f"{path}: map_precision must be city or venue")
        talks.append({
            "title": meta["title"], "venue": meta["venue"],
            "location": meta["location"], "date": date,
            "type": meta.get("type", "Talk"), "url": permalink,
            "latitude": lat, "longitude": lon, "precision": precision,
        })
    talks.sort(key=lambda item: (item["date"], item["url"]), reverse=True)
    return "// Generated by python3 talkmap.py; edit _talks/*.md, not this file.\nwindow.talkLocations = " + json.dumps(talks, ensure_ascii=False, indent=2) + ";\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if generated map data is stale; do not write")
    args = parser.parse_args()
    output = ROOT / "talkmap" / "org-locations.js"
    try:
        expected = build_data(ROOT / "_talks")
        if args.check:
            if not output.exists() or output.read_text(encoding="utf-8") != expected:
                print("Talk map data is stale. Run: python3 talkmap.py", file=sys.stderr)
                return 1
            print("Talk map data matches the published talk metadata.")
        else:
            output.write_text(expected, encoding="utf-8")
            print(f"Updated {output.relative_to(ROOT)}")
    except (ValueError, OSError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
